language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required
env:
  matrix: 
  global:
  - AZ_AD_SP_ID=http://mb-service-account
  - AZ_AD_TENANT=46947e84-c7c5-4572-bf44-0c0b2d9013b8
  - AZ_LOCATION=eastus
  - AZ_RG_BUILD=music-bot-build
  - AZ_RG_DEV=music-bot-dev
  - AZ_RG_INT_PREFIX=music-bot-int-
  - AZ_RG_PROD=music-bot-prod
  - secure: TbWOwjJ9LWargkmzKQ5D26mRctfGwk+SQeDqPfTS3GcsyTT5yuudVy99qhObnorccyJPYrUcxpsWLTSuqSy7oqNp3eUs6jinJRui8Yc8+Ml6/Vx0dGxbE3vfx6rxk49cM2RxRouhP3AjcExfGKQe+oPlxs2ufvz9N/2+lxZTuM7nnU4HMA6o1FyBrADYWbDpGif5eO+jq8RjNJGJ7tK/p9TwIpu5Wxny6IP5vc/w7nwG5brmEhoSxm0T3c3IUWxI23RByZ9GNAXlDKzRLRN8LwlyrOlWn4pUX33bW5puotEeabb50lIBvU4X5MhhnryxJEbZHhGk95aYtxT11ERZCSGgktJdH6yLT9/ObTFPfaCFjYmIRxfsRGVXt0iFNAxHRjLI8OKIDFGQ+hBTjap3/l9K+HeSbnZJRSVHRasaf7KiF4YurWMjzmFEYHEjgcwJcNimWDl+841ClBHJGe7yCtLNtjgrkmpvwBrzSU9C0UwfJ6wOKHdLgEkOKDY4aZEHYeaFfQuc4KKZP4Q2rGghczNQg7wpEofI4NFIJLRpl/R3vQtWHJ04mcB7AghtqjMToPh5eDbS8zFDlww9o4+qEg3mhhGI21zlE2qnd0MFvYMoQE7iAu5wS/2A6YBoB1435o8XBV9no3NhRKSDbowdH2DGGpGm40Hg4lBNtAoVWTI=
before_install:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/configure-azure-cli.sh; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then az login --service-principal -u $AZ_AD_SP_ID -p $AZ_AD_SP_PASS -t $AZ_AD_TENANT; fi'
script:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/integration-test.sh; fi'
after_script:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then az group delete -n $AZ_RG_BUILD-$TRAVIS_BUILD_NUMBER; fi'
before_deploy:
- './scripts/configure-azure-cli.sh'
- 'az login --service-principal -u $AZ_AD_SP_ID -p $AZ_AD_SP_PASS -t $AZ_AD_TENANT'
deploy:
# Deploy passing master builds to dev
- provider: script
  script: scripts/az-group-deploy.sh -g $AZ_RG_DEV -l $AZ_LOCATION -a src/arm
  on:
    branch: master
# Deploy to prod on git tag 'current-prod'
- provider: script
  script: scripts/az-group-deploy.sh -g $AZ_RG_PROD -l $AZ_LOCATION -a src/arm
  on:
    condition: 
    tags: true
notifications:
  slack:
    secure: b0m1mvBam5ika7DtHAyrobDMW+nmCAB/xmCBlgyxYqN0ko4UWU7UejkWULoNc16T3W5rl4acbsQJeJuh1WKIb0I1Vem65RMGN/eGVFWlm6Ijulp4p/bACyrEJdZ5su6FNo6oZE6Fo1OuijzAeRMTfLIvsCbkIzlM5sxmv47BTFva4lxXL+lDWoAQO9qhoC0RbWNTAPGYkX1uzC2MiriuxTvIv4rOgBN/38IV1Iss2/WYnfs9veyxj4rJIhY7Lyb1aYCdcwmFqThMwBN+zGaldYNFVjZqqAqOKZ4+fEo7srd/R1V3WUjJBDNSpTywwGRtRj2hdy2szv/YbUY5ZHrFKMwHNyFDsuCY+xDDK0MUsO1zVfdYun0ttzd13nuRgvUcrXKh4GMcY4Fj7wSBtITlr3KPCW8fbt4v7Sgy6DxwwFnjmtPfb7nj6EyTJpYwJBbXWTUsH8vVLcaPWBcqw2xIu0zYTD+AsVGm3UMYXx3K0yYJmLs5iubQiCLB6f/jzI/US5afUBPVyieyMEN1cwdV9U70llBUvO+Qya0zVAWyYRxeLDig34PABc8duskVVjC4RO4+YDIvtnhb4N1kK0EfIAax4hyw2BJKj4gmtvKB1YIognmmBOHycNd4thUqnH3ye+X6mDpJjmg180oyOU2zdkdbUzMqwVHpuQKZw2OXEx8=
