language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
env:
  matrix: 
  global:
  - AZ_AD_SP_ID=http://mb-service-account
  - AZ_AD_TENANT=46947e84-c7c5-4572-bf44-0c0b2d9013b8
  - AZ_LOCATION=eastus
  - AZ_RG_BUILD=music-bot-build
  - AZ_RG_DEV=music-bot-dev
  - AZ_RG_INT_PREFIX=music-bot-int-
  - AZ_RG_PROD=music-bot-prod
  - secure: TbWOwjJ9LWargkmzKQ5D26mRctfGwk+SQeDqPfTS3GcsyTT5yuudVy99qhObnorccyJPYrUcxpsWLTSuqSy7oqNp3eUs6jinJRui8Yc8+Ml6/Vx0dGxbE3vfx6rxk49cM2RxRouhP3AjcExfGKQe+oPlxs2ufvz9N/2+lxZTuM7nnU4HMA6o1FyBrADYWbDpGif5eO+jq8RjNJGJ7tK/p9TwIpu5Wxny6IP5vc/w7nwG5brmEhoSxm0T3c3IUWxI23RByZ9GNAXlDKzRLRN8LwlyrOlWn4pUX33bW5puotEeabb50lIBvU4X5MhhnryxJEbZHhGk95aYtxT11ERZCSGgktJdH6yLT9/ObTFPfaCFjYmIRxfsRGVXt0iFNAxHRjLI8OKIDFGQ+hBTjap3/l9K+HeSbnZJRSVHRasaf7KiF4YurWMjzmFEYHEjgcwJcNimWDl+841ClBHJGe7yCtLNtjgrkmpvwBrzSU9C0UwfJ6wOKHdLgEkOKDY4aZEHYeaFfQuc4KKZP4Q2rGghczNQg7wpEofI4NFIJLRpl/R3vQtWHJ04mcB7AghtqjMToPh5eDbS8zFDlww9o4+qEg3mhhGI21zlE2qnd0MFvYMoQE7iAu5wS/2A6YBoB1435o8XBV9no3NhRKSDbowdH2DGGpGm40Hg4lBNtAoVWTI=
before_install:
- sudo apt-get -y install python3-pip python-dev
- echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main"
  | sudo tee /etc/apt/sources.list.d/azure-cli.list
- sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893
- sudo apt-get install apt-transport-https
- sudo apt-get update -qq
- sudo apt-get install azure-cli
- az login --service-principal -u $AZ_AD_SP_ID -p $AZ_AD_SP_PASS -t $AZ_AD_TENANT
script:
- scripts/build-arm.sh -g $AZ_RG_BUILD-$ -v -l $AZ_LOCATION -a src/arm
- scripts/build-arm.sh -g $AZ_RG_BUILD-$ -l $AZ_LOCATION -a src/arm
deploy:
- provider: script
  script: scripts/az-group-deploy.sh -g $AZ_RG_DEV -l $AZ_LOCATION -a src/arm
  on:
    branch: master
- provider: 
