language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required
env:
  global:
  - AZ_AD_SP_ID=http://mb-service-account
  - AZ_AD_TENANT=46947e84-c7c5-4572-bf44-0c0b2d9013b8
  - AZ_LOCATION=eastus
  - AZ_RG_BUILD=MUSIC-BOT-BUILD
  - AZ_RG_DEV=MUSIC-BOT-DEV
  - AZ_RG_INT_PREFIX=MUSIC-BOT-INT-
  - AZ_RG_PROD=MUSIC-BOT-PROD
  - secure: TbWOwjJ9LWargkmzKQ5D26mRctfGwk+SQeDqPfTS3GcsyTT5yuudVy99qhObnorccyJPYrUcxpsWLTSuqSy7oqNp3eUs6jinJRui8Yc8+Ml6/Vx0dGxbE3vfx6rxk49cM2RxRouhP3AjcExfGKQe+oPlxs2ufvz9N/2+lxZTuM7nnU4HMA6o1FyBrADYWbDpGif5eO+jq8RjNJGJ7tK/p9TwIpu5Wxny6IP5vc/w7nwG5brmEhoSxm0T3c3IUWxI23RByZ9GNAXlDKzRLRN8LwlyrOlWn4pUX33bW5puotEeabb50lIBvU4X5MhhnryxJEbZHhGk95aYtxT11ERZCSGgktJdH6yLT9/ObTFPfaCFjYmIRxfsRGVXt0iFNAxHRjLI8OKIDFGQ+hBTjap3/l9K+HeSbnZJRSVHRasaf7KiF4YurWMjzmFEYHEjgcwJcNimWDl+841ClBHJGe7yCtLNtjgrkmpvwBrzSU9C0UwfJ6wOKHdLgEkOKDY4aZEHYeaFfQuc4KKZP4Q2rGghczNQg7wpEofI4NFIJLRpl/R3vQtWHJ04mcB7AghtqjMToPh5eDbS8zFDlww9o4+qEg3mhhGI21zlE2qnd0MFvYMoQE7iAu5wS/2A6YBoB1435o8XBV9no3NhRKSDbowdH2DGGpGm40Hg4lBNtAoVWTI=
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then 
  sudo apt-get -y install python3-pip python-dev;
  echo 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main' | sudo tee /etc/apt/sources.list.d/azure-cli.list;
  sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893;
  sudo apt-get install apt-transport-https;
  sudo apt-get update;
  sudo apt-get install azure-cli;
  az login --service-principal -u $AZ_AD_SP_ID -p $AZ_AD_SP_PASS -t $AZ_AD_TENANT;
  fi
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then 
  scripts/az-group-deploy.sh -g $AZ_RG_BUILD-$TRAVIS_BUILD_NUMBER -l $AZ_LOCATION -a src/arm;
  fi
after_script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then az group delete -y --no-wait -n $AZ_RG_BUILD-$TRAVIS_BUILD_NUMBER; fi
deploy:
# Deploy passing master builds to dev
- provider: script
  script: scripts/az-group-deploy.sh -g $AZ_RG_DEV -l $AZ_LOCATION -a src/arm
  on:
    branch: master
# Deploy to prod on git tag 'current-prod'
- provider: script
  script: scripts/az-group-deploy.sh -g $AZ_RG_PROD -l $AZ_LOCATION -a src/arm
  on:
    condition: $TRAVIS_TAG = current-prod
    tags: true
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: jwDxL8/7FLoSdG2BTwNQTvuFWXP/G+1s9VMVG2ZneBfz3sw6VrJzlCQc/vNJkM6SFNqqp15S7+qcwgGOJ3jcK2kU1eHdTm5fTvRugJCvU+HdHEzB7h4kHy7ZH/y4hoxrTdLS299Kq2K8XK9SZUSTEEwDWVg6prHeJTRWeJ0W9yIJ5knlFcWc1k73oglA0qvCoqRyeGM4u0wtKqzO8y4v/Kg2Jqa77YtkX55BUF13eQOqstfA2iUUnEMjCdK7rQtGGtnJMXEmNeVmrmFBdH/lz8QtUJiJjieS3IsGeB6U8UAnuSxMoOzYlwmClAQa8o1V4P3MbPGahx/yQm3fEciflNX72U8d9XQS2mLqm/gSf0/8IONuhLjox5arSVrNI3zCm7IuXtRoEFPs9RvvzjiEY8S7tsuY0PcK1iIeDCXQ9sdcTsUXU9RcLAJmq9K6e934EJFU3srOZ9fGwO7/GIGSDE6ekUtCl8T7hCNlkCzI4saz2bP/VkNigPaIcZ/lZzqpHBjC1WLr0MKY7w6NqE8jFtMoCYhBnUdPkkMle5ZDcDFy27AgoYJgKX2TenZdNMN8v0lEHAbgvJme1Nngq0/GeVhhG8YFK0o+y5NasTWQKMVffNm+ti46SMWlGNE7Ci++Q9iedh/qmOOdvwMwnZ16Hu16MzSY40d5KfZ5b61tpuE=
