version: 1.0.0.{build}
image: Visual Studio 2017 Preview
assembly_info:
  patch: true
branches:
  only:
    - master
environment:
  AZ_AD_SP_ID: http://musicbotsvc
  AZ_AD_TENANT: 46947e84-c7c5-4572-bf44-0c0b2d9013b8
  AZ_AD_SP_PASS:
    secure: QBSDpMZyT8QNWCo1R8M6o7+Umvo61xZjMnRIAp2a/eM=
  AZ_LOCATION: eastus
  AZ_RG_BUILD: MUSIC-BOT-BUILD
  AZ_RG_DEV: MUSIC-BOT-DEV
  AZ_RG_INT_PREFIX: MUSIC-BOT-INT-
  AZ_RG_PROD: MUSIC-BOT-PROD
  GIT_ACCESS_TOKEN:
    secure: /8nuu389OsrB4Ylkb0aM6AsXqVTYfhqMibLEH8SZDNAEOIMPe2SiR8Im/jFX6rQ2
install:
  - npm install -g newman
before_build:
  - ps: $pass = ConvertTo-SecureString $env:AZ_AD_SP_PASS -AsPlainText -Force
  - ps: $cred = New-Object -TypeName pscredential -ArgumentList $env:AZ_AD_SP_ID, $pass
  - ps: Login-AzureRmAccount -Credential $cred -ServicePrincipal -TenantId $env:AZ_AD_TENANT
build_script: 
  # Restore and build
  - nuget restore
  - msbuild MusicBot.Backend.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="MusicBot-Functions.zip"

  # Prep for integration test - push branch to github
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GIT_ACCESS_TOKEN):x-oauth-basic@github.com`n"
  - git checkout -b %AZ_RG_INT_PREFIX%%APPVEYOR_BUILD_NUMBER%
  - git push -u origin %AZ_RG_INT_PREFIX%%APPVEYOR_BUILD_NUMBER%

  # Deploy resources and test
  - ps: ./src/arm/Deploy-AzureResourceGroup.ps1 -ArtifactStagingDirectory src/arm -ResourceGroupLocation $env:AZ_LOCATION -OtherParams @{ resourcePrefix = "$env:AZ_RG_INT_PREFIX$env:APPVEYOR_BUILD_NUMBER"; branch = "$env:AZ_RG_INT_PREFIX$env:APPVEYOR_BUILD_NUMBER"; }
  - ps: if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
  - newman run test/func/musicbot.postman_collection.json -e test/func/integration-test.postman_environment.json --global-var "BaseUrl=https://%AZ_RG_INT_PREFIX%%APPVEYOR_BUILD_NUMBER%.azurewebsites.net"
on_finish:
  - ps: Start-Job -ScriptBlock { Remove-AzureRmResourceGroup -Name $env:AZ_RG_INT_PREFIX$env:APPVEYOR_BUILD_NUMBER -Force }
  - git push origin --delete %AZ_RG_INT_PREFIX%%APPVEYOR_BUILD_NUMBER%
  - ps: Start-Sleep -s 5 # Wait for the script to trigger the call to azure
artifacts:
  - path: src/arm
    name: ARM Templates
  - path: src/func/MusicBot-Functions.zip
    name: Functions App