version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk-jessie
    steps:
      - checkout
  test:
    docker:
      - image: microsoft/dotnet:2.0-sdk-jessie
    steps:
      - checkout
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test